# Generated by Django 5.0.3 on 2024-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_songs_options_songs_listened_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albom',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='albom',
            name='popular',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='albom',
            index=models.Index(fields=['id'], name='music_albom_id_fdca22_idx'),
        ),
    ]
